In [2]:
import pandas as pd
import numpy as np 
from scipy import stats

# Préparation des données

In [3]:
data=pd.read_csv("titanic.csv");
#1/Enlever la variable "Fare"
data=data.drop(columns=['Fare'],axis=1);
#2/ Recoder la variable sex en variable binaire (male= 0, female=1)
data.Sex[data.Sex == 'male'] = 0;
data.Sex[data.Sex == 'female'] = 1;
#3/ Remplacer les valeurs manquantes dans la variable age par 0
data.Age=data.Age.replace(np.NaN,0);
data.Embarked[data.Embarked == 'C'] = 67;
#4/Controlez le nombre d’entrees, le nombre de champs et leur étendue.
#data.describe()
#5/ Transformer les variables Sex et Embarxed en int
data.Sex=data.Sex.astype(int);
data.Embarked= data.Embarked.astype(int);



/Users/macbookpro/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/macbookpro/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/macbookpro/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


# Tableaux de contingence

In [4]:
pd.crosstab(data.Survived, data.Sex)

Sex         0    1
Survived          
0          81  468
1         233  109

In [17]:
data.describe()

Survived      Pclass         Sex         Age       SibSp       Parch  \
count  891.000000  891.000000  891.000000  891.000000  891.000000  891.000000   
mean     0.383838    2.308642    0.647587   23.799293    0.400673    0.345679   
std      0.486592    0.836071    0.477990   17.596074    0.637727    0.663266   
min      0.000000    1.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000    2.000000    0.000000    6.000000    0.000000    0.000000   
50%      0.000000    3.000000    1.000000   24.000000    0.000000    0.000000   
75%      1.000000    3.000000    1.000000   35.000000    1.000000    0.000000   
max      1.000000    3.000000    1.000000   80.000000    2.000000    2.000000   

         Embarked  
count  891.000000  
mean    79.774411  
std      6.231278  
min     67.000000  
25%     81.000000  
50%     83.000000  
75%     83.000000  
max     83.000000

In [18]:
pd.crosstab(data.Survived, data.Embarked)

Embarked  67  81   83
Survived             
0         75  47  427
1         95  30  217

In [1]:
crosstab=pd.crosstab(data.Survived, data.Sex)
#Z=pd.crosstab(data.Survived, data.Pclass)
#Sum_Survived_0 = np.sum(Z.as_matrix()[0,:])
#Sum_Survived_1 = np.sum(Z.as_matrix()[1,:])

#Sum_Pclass_1 = np.sum(Z.as_matrix()[:,0])
#Sum_Pclass_2 = np.sum(Z.as_matrix()[:,1])
#Sum_Pclass_3 = np.sum(Z.as_matrix()[:,2])



NameError: name 'pd' is not defined

# Dépendences des variables

In [48]:
[chi2, pvalue, dof, ex]= stats.chi2_contingency(crosstab)
 

In [49]:
chi2

260.71702016732104

In [23]:
crosstab 

Pclass      1   2    3
Survived              
0          80  97  372
1         136  87  119

In [32]:
Cr=crosstab.as_matrix()

In [44]:
Cr.T@Cr

array([[ 24896,  19592,  45944],
       [ 19592,  16978,  46437],
       [ 45944,  46437, 152545]])

In [37]:
Cr

array([[ 80,  97, 372],
       [136,  87, 119]])

In [43]:
crosstab

Pclass      1   2    3
Survived              
0          80  97  372
1         136  87  119

In [45]:
Cr.T@Cr

array([[ 24896,  19592,  45944],
       [ 19592,  16978,  46437],
       [ 45944,  46437, 152545]])

In [5]:
data.head()

Survived  Pclass  Sex   Age  SibSp  Parch  Embarked
0         0       3    1  22.0      1      0        83
1         1       1    0  38.0      1      0        67
2         1       3    0  26.0      0      0        83
3         1       1    0  35.0      1      0        83
4         0       3    1  35.0      0      0        83

In [9]:
data=pd.read_csv("titanic.csv");
#2/ Recoder la variable sex en variable binaire (male= 0, female=1)
data.Sex[data.Sex == 'male'] = 0;
data.Sex[data.Sex == 'female'] = 1;
#3/ Remplacer les valeurs manquantes dans la variable age par 0
data.Age=data.Age.replace(np.NaN,0);
data.Embarked[data.Embarked == 'C'] = 67;
#4/Controlez le nombre d’entrees, le nombre de champs et leur étendue.
#data.describe()
#5/ Transformer les variables Sex et Embarxed en int
data.Sex=data.Sex.astype(int);
#data.Embarked= data.Embarked.astype(int);

data=data[['Survived','Pclass','Sex','Age']]
data.head()

/Users/macbookpro/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/macbookpro/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/macbookpro/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


Survived  Pclass  Sex   Age
0         0       3    0  22.0
1         1       1    1  38.0
2         1       3    1  26.0
3         1       1    1  35.0
4         0       3    0  35.0